### ISSUE TITLE
Stworzyć własny wyjątek dotyczący persystencji i opakować wszystkie runtime exception z klasy BookRepository

### ISSUE THREAD

**Issue by krzysztofkramarz** [marcinogo/robot#118]
W tej chwili klasa BookRepository rzuca w wielu miejscach runtiime exceptiony. Trzeba stworzyć swój wyjątek roszerzający Eception , łapać wszystkie runtimy ( sa w wielui miejscach w tej klasie) w try catchach i wyrzucać nasz wyjątek, opakować  w ten nasz wyjątek ruintimowy, i dac klauzulę throws NaszWyjątek.

**Comment by marcinogo** [comment]
Zadanie porzócone ponieważ pomysłodawca opóćił projekt i nie widzimy sensu tych poczynań.
