### ISSUE TITLE
Mvn site - naprawić. Wyrzuca błędy przy budowie

### ISSUE THREAD

**Issue by Ozonek95** [marcinogo/robot#140]
Podczas wykonywania site wyrzuca error. 

[WARNING] Unable to create Maven project from repository for artifact commons-logging:commons-logging-api:jar:1.1
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'distributionManagement.status' must not be specified. @ line 163, column 13

 1 problem was encountered while building the effective model for commons-logging:commons-logging-api:1.1
[ERROR] 'distributionManagement.status' must not be specified. @ line 163, column 13

Pojawia się również [INFO] związane z Eclipse:
[INFO] Could not build project for: lifecycle-mapping:Error resolving project artifact: Failure to find org.eclipse.m2e:lifecycle-mapping:pom:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced for project org.eclipse.m2e:lifecycle-mapping:pom:1.0.0
org.apache.maven.project.ProjectBuildingException: Error resolving project artifact: Failure to find org.eclipse.m2e:lifecycle-mapping:pom:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced for project org.eclipse.m2e:lifecycle-mapping:pom:1.0.0

Oraz [INFO] z JDepend
[INFO] Generating "JDepend" report       --- jdepend-maven-plugin:2.0:generate-no-fork
Unknown constant: 18

**Comment by marcinogo** [comment]
Znany problem: https://github.com/FasterXML/jackson-module-scala/issues/393 oraz https://stackoverflow.com/questions/51069767/maven-unknown-packaging-bundle-error-from-a-dependency-packaging-as-bundle/51070617.

Podejmie się próbę użycia maven-bundle-plugin w celu zażegnania problemu. W innym wypadku nalezy go zignorować do czasu pojawienia się nowszysch wersji: maven-project-info-reports-plugin oraz maven-site-plugin

**Comment by marcinogo** [comment]
Nie udało się naprawić tych ostrzeżeń. Przypuszczalnie nalezy się z nimi pogodzić i zaakceptować

**Comment by marcinogo** [comment]
Nie znalazłem nic konkretnego o INFO Generating "JDepend" report --- jdepend-maven-plugin:2.0:generate-no-fork
Unknown constant: 18

**Comment by Krzysztof-Lempicki** [comment]
Gdy dorzuciłem sobie do parent **pom**:

`    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>3.0.0</version>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>dependencies</report>
                            <report>team</report>
                            <report>mailing-lists</report>
                            <report>ci-management</report>
                            <report>issue-management</report>
                            <report>licenses</report>
                            <report>scm</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>`

To rozwiązało wszystkie problemy dotyczące odpalania `site`.
