### ISSUE TITLE
Testy wydajnościowe Jmeter

### ISSUE THREAD

**Issue by TwojaTata** [marcinogo/robot#233]
- [ ] Do czego dokładnie służy
- [x] Co jest potrzebne aby pisać w tym testy
- [x] wady
- [ ] zalety
- [ ] przeciwskazania do użycia
- [x] Przykładowe testy

**Comment by atrzewik** [comment]
Słaba dokumentacja, która nie pozwala nie bezproblemowe użycie jmeter za pomocą samego mavena -  w przypadku GUI nie ma problemu.
Dodatkwo problem z zastosowaniem autentykacji na H2, przez co problem ze sprawdzeniem jmeter na podstawie naszego Robota.

**Comment by atrzewik** [comment]
Podjęcie decyzji o zastosowaniu Gatlinga
