### ISSUE TITLE
sprawdzenie api

### ISSUE THREAD

**Issue by sehta7** [marcinogo/robot#79]
Sprawdzenie monumentalnego api księgarni znalezionej przez Wiktora. Szukamy 1 księgarni z restowym API, koniecznie musi mieć informacje o promocjach.

**Comment by marcinogo** [comment]
Obiecująca strona z listą API księgarnii: https://www.programmableweb.com/news/53-books-apis-google-books-goodreads-and-sharedbook/2012/03/13

**Comment by kamroj** [comment]
Nie znalazłem żadnej księgarni udostępniającej API. Inisteje natomaist coś takiego jak google API books. Natomiast jest ono jakieś turbo dziwne i totalne nie intuicyjne. Problemy jakie widzę:
- dziwne nazwenictwo zmiennych w pliku JSON,
- czasami jest cena czasem nie ( może przez to że książka jest za darmo? ),
- ogólnie nie wiem czy da się pobrać wszystkie książki chociażby z jednej kategori (jest chyba jakieś ograniczenie),
- trzeba stworzyć konto, bądz użyć naszego istniejącego jarobot, żeby dostać uprawnienia do korzystania z API,
- patrzyłem na przykładowy kod gościa z googla i wygląda tragicznie (link poniżej).

Także nie wiem za bardzo czy próbujemy iść w to czy jednak szukamy czegoś innego ( może ktoś na coś konkretnego natrafi ).

Link do implementacji : https://github.com/google/google-api-java-client-samples/blob/master/books-cmdline-sample/src/main/java/com/google/api/services/samples/books/cmdline/BooksSample.java

**Comment by LIttleAncientForestKami** [comment]
Proponuję:

1. Google Books API
2. Wykorzystać ich `salableInfo` i jak jest `not_for_sale` to właśnie to wyświetlić. 
3. Jak na sprzedaż, po prostu wyświetlić cenę. 

URLe do przeglądu:

1. Przykładowa książka nie na sprzedaż: https://www.googleapis.com/books/v1/volumes/5W-ChoTedM4C
2. Lektura przed kodowaniem do API Google Books: https://developers.google.com/books/docs/v1/getting_started
3. Google Books dla programistów - przykłady integracji, przewodniki, itp.: https://developers.google.com/books/

I z tą myślą można to zamknąć.
